cosmos/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^', include('country.urls', namespace='country')),
    url(r'^country/', include('country.urls', namespace='country')),
    url(r'^lab/', include('lab.urls', namespace='lab')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

country/urls.py
from django.conf.urls import url

from . import views
from lab import views as lab_views

app_name = 'country'
urlpatterns = [
    # ex: /country/
    # url(r'^$', views.index, name='index'),
    # ex: /country/5/
    url(r'^$', views.countries, name='countries'),
    url(r'^(?P<country_id>[0-9]+)/$', views.country_detail, name='country_detail'),
    url(r'^list/$', views.countries, name='countries'),
    url(r'^(?P<country_id>[0-9]+)/labs/$', lab_views.labs_by_country, name='labs_by_country'),
    url(r'^(?P<country_id>[0-9]+)/tests/$', lab_views.tests_by_country, name='tests_by_country'),
]

lab/urls.py
from django.conf.urls import url

from . import views

app_name = 'lab'
urlpatterns = [
    # ex: /lab/
    # url(r'^$', views.index, name='index'),
    # ex: /lab/5/
    url(r'^(?P<lab_id>[0-9]+)/$', views.lab_detail, name='lab_detail'),
]

country/models.py
from django.db import models
from django.contrib.auth.models import User


class Society(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()

    def __str__(self):
        return self.name


class ExternalData(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    icon = models.FileField(upload_to='projects', null=True)

    def __str__(self):
        return self.name


class Country(models.Model):
    hvp_status_choices = (
        ('Interim', 'Interim'),
    )
    name = models.CharField(max_length=200)
    region = models.CharField(max_length=80)
    hvp_status = models.CharField(
        choices=hvp_status_choices,
        max_length=32,
        default='Interim',
    )
    hvp_date = models.DateField()
    background = models.TextField()
    standard_regulation = models.TextField()
    licensing = models.CharField(max_length=200)
    personnel = models.ManyToManyField(User, related_name='personnel')
    representatives = models.ManyToManyField(User, related_name='representative')
    genetics_society = models.CharField(max_length=200)
    genetics_society_url = models.URLField()
    other_societies = models.ManyToManyField(Society)
    external_data = models.ManyToManyField(ExternalData)
    projects = models.ManyToManyField(Project)

    dna_analysis_regulation = models.TextField()
    dna_storage_regulation = models.TextField()
    dna_reporting_regulation = models.TextField()

    def __str__(self):
        return self.name

lab/models.py
from django.db import models
from country.models import Country


class Service(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Lab(models.Model):
    name = models.CharField(max_length=200)
    institution = models.CharField(max_length=200, null=True, blank=True)
    abbreviation = models.CharField(max_length=20, null=True, blank=True)
    website = models.URLField()
    country = models.ForeignKey(Country)
    phone = models.CharField(max_length=20, null=True, blank=True)
    fax = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    zip = models.CharField(max_length=16)
    data_sharing = models.BooleanField()
    last_updated = models.DateTimeField(auto_now=True)
    gtr_lab_id = models.PositiveIntegerField()
    services = models.ManyToManyField(Service)

    def __str__(self):
        return self.name


class Personnel(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)
    role = models.CharField(max_length=64)
    phone = models.CharField(max_length=20, null=True, blank=True)
    fax = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField()
    date_joined = models.DateField()

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)


class Certification(models.Model):
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    number = models.CharField(max_length=32)
    date_expiration = models.DateField()

    def __str__(self):
        return self.name


class Condition(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class GeneAnalyte(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Method(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class LabTest(models.Model):
    name = models.CharField(max_length=255)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)
    conditions = models.ManyToManyField(Condition)
    gene_analytes = models.ManyToManyField(GeneAnalyte)
    methods = models.ManyToManyField(Method)

    def __str__(self):
        return self.name

country/views.py
from django.shortcuts import render, get_object_or_404

from .models import Country

def country_detail(request, country_id):
    country = get_object_or_404(Country, pk=country_id)
    test_count = 345
    lab_count = 17
    return render(request, 'country/summary.html', 
        {
            'country': country,
            'test_count': test_count,
            'lab_count': lab_count,
        })


def countries(request):
    return render(request, 'country/countries.html',
        {
            'countries': Country.objects.all(),
        })

lab/views.py
from django.shortcuts import render, get_object_or_404

from .models import Lab, LabTest
from country.models import Country

def lab_detail(request, lab_id):
    lab = get_object_or_404(Lab, pk=lab_id)
    return render(request, 'lab/detail.html', 
        {
            'lab': lab,
        })


def labs_by_country(request, country_id):
    country = get_object_or_404(Country, pk=country_id)
    return render(request, 'lab/country_labs.html', 
        {
            'country': country,
            'labs': country.lab_set.all(),
        })


def tests_by_country(request, country_id):
    country = get_object_or_404(Country, pk=country_id)
    return render(request, 'lab/country_tests.html',
        {
            'country': country,
            'tests': LabTest.objects.filter(lab__country_id=country_id),
        })

cosmos/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load staticfiles %}

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block pagetitle %}cosmos{% endblock pagetitle %}</title>

  <!-- Bootstrap Core CSS -->
  <link href="{% static 'dashboard/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- MetisMenu CSS -->
  <link href="{% static 'dashboard/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="{% static 'dashboard/dist/css/sb-admin-2.css' %}" rel="stylesheet">

  <!-- Morris Charts CSS -->
  <link href="{% static 'dashboard/vendor/morrisjs/morris.css' %}" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="{% static 'dashboard/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  {% block extrahead %}
  {% endblock extrahead %}

</head>

<body>

  <div id="wrapper">

    {% block navbar %}
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'country:countries' %}">Cosmos</a>
      </div>
      <!-- /.navbar-header -->

      <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
          <ul class="nav" id="side-menu">
            <li>
              <a href="{% url 'country:countries' %}"><i class="fa fa-arrow-left fa-fw"></i> Back to Map</a>
            </li>
            <li>
              &nbsp;
            </li>
            <li>
              <a href="{% url 'country:country_detail' country_id %}"><i class="fa fa-dashboard fa-fw"></i> Summary</a>
            </li>
            <li>
              <a href="{% url 'country:tests_by_country' country_id %}"><i class="fa fa-flask fa-fw"></i> Available Tests &amp; Genes</a>
            </li>
            <li>
              <a href="{% url 'country:labs_by_country' country_id %}"><i class="fa fa-hospital-o fa-fw"></i> Clinical Laboratories</a>
            </li>
            <li>
              <a href="#"><i class="fa fa-institution fa-fw"></i> Societies &amp; Organisations</a>
            </li>
            <li>
              <a href="#"><i class="fa fa-users fa-fw"></i> HVP Consortium Members</a>
            </li>
            <li>
              <a href="#"><i class="fa fa-legal fa-fw"></i> Regulatory Instruments</a>
            </li>
          </ul>
        </div>
        <!-- /.sidebar-collapse -->
      </div>
      <!-- /.navbar-static-side -->
    </nav>
    {% endblock navbar %}

    <div id="page-wrapper">
    {% block content %}
    {% endblock content %}
    </div>

    {% block extrafoot %}
    {% endblock extrafoot %}

  </div>
  <!-- /#wrapper -->

  <!-- jQuery -->
  <script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  <!-- Metis Menu Plugin JavaScript -->
  <script src="{% static 'dashboard/vendor/metisMenu/metisMenu.min.js' %}"></script>

  <!-- Custom Theme JavaScript -->
  <script src="{% static 'dashboard/dist/js/sb-admin-2.js' %}"></script>

  {% block extrajs %}
  {% endblock extrajs %}

</body>

</html>

country/templates/country/countries.html
{% extends "dashboard/base.html" %}

{% block pagetitle %}
Cosmos
{% endblock pagetitle %}

{% load staticfiles %}

{% block navbar %}
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'country:countries' %}">Cosmos</a>
      </div>
      <!-- /.navbar-header -->
    </nav>
{% endblock navbar %}

{% block content %}
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">Countries</h1>
          <div class="panel panel-default">
            <div class="panel-body">
              <a href="#"><img style="margin: auto;" src="{% static 'dashboard/dist/img/wrldnanb.gif' %}"></a>
            </div>
          </div>
        </div>
      <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->

      <div class="row">
        <div class="col-lg-12">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
              <thead>
                <tr>
                  <th scope="col">Country</th>
                  <th scope="col">Region</th>
                </tr>
              </thead>
              <tbody>
                {% for c in countries %}
                    <tr><td><a href="{% url 'country:country_detail' c.id %}">{{ c.name }}</a></td><td>{{ c.region }}</td></tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
        <!-- /.row -->
{% endblock content %}

{% block extrajs %}
  <!-- DataTables JavaScript -->
  <script src="{% static 'dashboard/vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/datatables-plugins/dataTables.bootstrap.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/datatables-responsive/dataTables.responsive.js' %}"></script>

  <!-- Page-Level Demo Scripts - Tables - Use for reference -->
  <script>
  $(document).ready(function() {
    $('#dataTables-example').DataTable({
      responsive: true
    });
  });
  </script>

  <!-- Custom Theme JavaScript -->
  <script src="{% static 'dashboard/dist/js/sb-admin-2.js' %}"></script>
{% endblock extrajs %}

country/templates/country/detail.html
{% extends "dashboard/base.html" %}

{% block pagetitle %}
{{ country.name }} - Cosmos
{% endblock pagetitle %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><img src="http://www.humanvariomeproject.org/images/flags/GB.png" alt="Flag of {{ country.name }}"> {{ country.name }} <span class="badge">HVP Country Node</span></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

        <!-- /.row -->
        <div class="row">
          <div class="col-lg-6">
          <!-- Summary -->
            <div class="panel-group" id="summary-accordion" role="tablist" aria-multiselectable="true">

              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                  <h2 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#summary-accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Background</a></h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                  <div class="panel-body">
                    <p>{{ country.background }}</p>
                  </div>
                </div>
              </div>
              <!-- /. Panel One -->

              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingTwo">
                  <h2 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" role="button" data-parent="#summary-accordion" href="#collapseTwo" aria-expanded="false" aria-controls"collapseTwo">Laboratory Standards and Regulations</a></h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                  <div class="panel-body">
                    <p>{{ country.standard_regulation }}</p>
                  </div>
                </div>
              </div>
              <!-- ./ Panel Two -->

              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingThree">
                  <h2 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" role="button" data-parent="#summary-accordion" href="#collapseThree" aria-expanded="false" aria-controls"collapseThree">Laboratory Personnel and Licensing</a></h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                  <div class="panel-body">
                    <p>{{ country.licensing }}</p>
                  </div>
                </div>
              </div>
              <!-- ./ Panel Three -->

              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingFour">
                  <h2 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" role="button" data-parent="#summary-accordion" href="#collapseFour" aria-expanded="false" aria-controls"collapseFour">DNA Analysis and Interpretation Practices and Regulations</a></h4>
                </div>
                <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
                  <div class="panel-body">
                    <p>{{ country.dna_analysis_regulation }}</p>
                  </div>
                </div>
              </div>
              <!-- ./ Panel Four -->

              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingFive">
                  <h2 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" role="button" data-parent="#summary-accordion" href="#collapseFive" aria-expanded="false" aria-controls"collapseFive">DNA Storage Practices and Regulations</a></h4>
                </div>
                <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
                  <div class="panel-body">
                    <p>{{ country.dna_storage_regulation }}</p>
                  </div>
                </div>
              </div>
              <!-- ./ Panel Five -->

              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingSix">
                  <h2 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" role="button" data-parent="#summary-accordion" href="#collapseSix" aria-expanded="false" aria-controls"collapseSix">DNA Data Reporting and Sharing Regulations</a></h4>
                </div>
                <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
                  <div class="panel-body">
                    <p>{{ country.dna_reporting_regulation }}</p>
                  </div>
                </div>
              </div>
              <!-- ./ Panel Six -->

            </div>
            <!-- /.panelgroup -->

          </div>
          <!-- /.col-lg-6 -->

          <div class="col-lg-6">
            <div class="row">
            <!-- Country Summary Row -->
              <div class="col-lg-12">
                <div class="panel panel-info">
                  <div class="panel-heading">
                    <h2 class="panel-title">General Information</h2>
                  </div>
                  <table class="table">
                    <tbody>
                      <tr>
                        <th scope="col">Region</th>
                        <td>{{ country.region }}</td>
                      <tr>
                        <th scope="row">HVP Country Node Status</th>
                        <td>{{ country.hvp_status }} ({{ country.hvp_date }})</td>
                      </tr>
                      <tr>
                        <th scope="row">ICCAC Representative</th>
                        <td>
                        {% for p in country.representatives.all %}
                            {{ p.first_name }} {{ p.last_name }}<br/>
                        {% endfor %}
                        </td>
                      </tr>
                      <tr>
                        <th scope="row">External Data</th>
                        <td>
                        {% for e in country.external_data.all %}
                            <a href="{{ e.url }}" target="_blank">{{ e.name }}</a><br/>
                        {% endfor %}
                        </td>
                      </tr>
                      <tr>
                        <th scope="row">National Human Genetics Society</th>
                        <td>
                            <a href="{{ country.genetics_society_url }}" target="_blank">{{ country.genetics_society }}</a>
                        </td>
                      </tr>
                      <tr>
                        <th scope="row">Others Societies</th>
                        <td>
                        {% for e in country.other_societies.all %}
                            <a href="{{ e.url }}" target="_blank">{{ e.name }}</a><br/>
                        {% endfor %}
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            <div class="row">
            <!-- PWI Involvement Row -->
              <div class="col-md-12">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h2 class="panel-title">Project-Wide Initiative Involvement</h3>
                  </div>
                  <table class="table">
                    <tr>
                      {% for p in country.projects.all %}
                        <td class="text-center" style="vertical-align:middle">
                          <a href="{{ p.url }}" target="_blank"><img src="{{ p.icon.url }}"></a>
                        </td>
                      {% endfor %}
                    </tr>
                  </table>
                </div>
              </div>
            </div>

            <div class="row">
            <!-- Test and Lab Count Row -->
              <div class="col-md-6">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <div class="row">
                      <div class="col-xs-3">
                        <i class="fa fa-flask fa-5x"></i>
                      </div>
                      <div class="col-xs-9 text-right">
                        <div class="huge">{{ test_count }}</div>
                        <div>Available Tests</div>
                      </div>
                    </div>
                  </div>
                  <div class="panel-footer">
                    <a href="tests.html">
                      <span class="pull-left">View Details</span>
                      <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    </a>
                    <div class="clearfix"></div>
                  </div>
                </div>
                <!-- /.panel -->
              </div>

              <div class="col-md-6">
                <div class="panel panel-green">
                  <div class="panel-heading">
                    <div class="row">
                      <div class="col-xs-3">
                        <i class="fa fa-hospital-o fa-5x"></i>
                      </div>
                      <div class="col-xs-9 text-right">
                        <div class="huge">{{ lab_count }}</div>
                        <div>Clinical Labs</div>
                      </div>
                    </div>
                  </div>
                  <div class="panel-footer">
                    <a href="labs.html">
                      <span class="pull-left">View Details</span>
                      <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    </a>
                    <div class="clearfix"></div>
                  </div>
                </div>
                <!-- /.panel -->
              </div>
            </div>
            <!-- /.row -->
          </div>
          <!-- /.col-lg-6 -->
        </div>
        <!-- /.row -->

{% endblock content %}

lab/templates/lab/country_labs.html
{% extends "dashboard/base.html" %}

{% block pagetitle %}
{{ country.name }} - Labs
{% endblock pagetitle %}

{% load staticfiles %}

{% block navbar %}
    {% with country.id as country_id %}
    {{ block.super }}
    {% endwith %}
{% endblock navbar %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ country.name }} <small>Clinical labs</small> <span class="badge">HVP Country Node</span></h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
          <div class="col-lg-12">
            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
              <thead>
                <tr>
                  <th>Laboratory Name</th>
                  <th>Website</th>
                  <th>Shares data</th>
                  <th># of tests</th>
                  <th>Last Updated</th>
                </tr>
              </thead>
              <tbody>
                {% for lab in labs %}
                <tr>
                  <td>{{ lab.name }}</td>
                  <td><a href="{{ lab.website }}" target="_blank">{{ lab.website }}</td>
                  <td>{{ lab.data_sharing }}</td>
                  <td>{{ lab.labtest_set.count }}</td>
                  <td>{{ lab.last_updated }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <!-- /.table-responsive -->
          </div>
        </div>
        <!-- /.row -->

{% endblock content %}

{% block extrajs %}
  <!-- DataTables JavaScript -->
  <script src="{% static 'dashboard/vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/datatables-plugins/dataTables.bootstrap.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/datatables-responsive/dataTables.responsive.js' %}"></script>

  <!-- Page-Level Demo Scripts - Tables - Use for reference -->
  <script>
  $(document).ready(function() {
    $('#dataTables-example').DataTable({
      responsive: true
    });
  });
  </script>

  <!-- Custom Theme JavaScript -->
  <script src="{% static 'dashboard/dist/js/sb-admin-2.js' %}"></script>
{% endblock extrajs %}

lab/templates/lab/detail.html
{% extends "dashboard/base.html" %}

{% block pagetitle %}
{{ lab.name }} - Cosmos
{% endblock pagetitle %}

{% load staticfiles %}

{% block navbar %}
    {% with country.id as country_id %}
    {{ block.super }}
    {% endwith %}
{% endblock navbar %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ lab.name }}</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-body">
                <p>{{ lab.name }}{% if lab.abbreviation %}, {{ lab.abbreviation }}{% endif %}<br/>
                {% if lab.institution %}{{ lab.institution }}<br/>{% endif %}
                {% if lab.city %}{{ lab.city }}<br/>{% endif %}
                {{ lab.country }} {{ lab.zip }}<br/>
                Phone: <a href="tel:{{ lab.phone }}">{{ lab.phone }}</a><br/>
                Fax: {{ lab.fax }}<br/>
                Email: <a href="mailto:{{ lab.email }}">{{ lab.email }}</a><br/>
                Website: <a href="{{ lab.website }}" target="_blank">{{ lab.website }}</a><br/>
                <span class="pull-right">GTR Lab ID: {{ lab.gtr_lab_id }}</span><p>
              </div>
            </div>
          </div>
        </div>
        <!-- /.row -->
        <div class="row">
          <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h2 class="panel-title">Personnel</h2>
              </div>
              <div class="panel-body">

                <ul class="list-unstyled">
                {% for p in lab.personnel_set.all %}
                <li style="padding-bottom:1em;">
                    {{ p.first_name }} {{ p.last_name }}, {{ p.role }}<br>
                    Phone: {{ p.phone }}<br>
                    Fax: {{ p.fax }}<br>
                    Email: <a href="mailto:{{ p.email }}" target="_blank">{{ p.email }}</a>
                </li>
                {% endfor %}
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h2 class="panel-title">Conditions and tests</h2>
              </div>
              <div class="table-responsive">
                <table class="table table-striped table-hover">
                  <tbody>
                    {% for t in lab.labtest_set.all %}
                    <tr><td>{{ t.name }}</td></tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">List of Services</h2>
                </div>
                <div class="panel-body">
                    <ul class="list-unstyled">
                    {% if lab.services.all %}
                    {% for s in lab.services.all %}
                        <li style="padding-bottom:1em;">{{ s.name }}</li>
                    {% endfor %}
                    {% else %}
                        <li style="padding-bottom:1em;">This lab has no services.</li>
                    {% endif %}
                    </ul>
                </div>
            </div>

            <div class="panel panel-default">
              <div class="panel-heading">
                <h2 class="panel-title">List of Certifications</h2>
              </div>
              <div class="panel-body">
                <ul class="list-unstyled">
                {% if lab.certification_set.all %}
                {% for c in lab.certification_set.all %}
                    <li style="padding-bottom:1em;">{{ c.name }}, Number: {{ c.number }}, Expiration date: {{ c.date_expiration }}</li>
                {% endfor %}
                {% else %}
                    <li style="padding-bottom:1em;">This lab has no certification.</li>
                {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
{% endblock content %}

{% block extrajs %}

  <!-- DataTables JavaScript -->
  <script src="{% static 'dashboard/vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/datatables-plugins/dataTables.bootstrap.min.js' %}"></script>
  <script src="{% static 'dashboard/vendor/datatables-responsive/dataTables.responsive.js' %}"></script>

  <!-- Page-Level Scripts - Tables - Use for reference -->
  <script>
  $(document).ready(function() {
    $('#dataTables-example').DataTable({
      responsive: true
    });
  });
  </script>

  <!-- Custom Theme JavaScript -->
  <script src="{% static 'dashboard/dist/js/sb-admin-2.js' %}"></script>

{% endblock extrajs %}